version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:password@db:5432/nest
      - JWT_SECRET='R2D2paradoxo1914#'
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - .:/app
  prisma:
    image: ghcr.io/prisma/prisma:latest
    container_name: prisma
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/nest
    volumes:
      - ./prisma:/app/prisma
    command: ["prisma", "migrate", "deploy"]
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data